events {
    worker_connections 1024;
}

http {
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=minio_cache:10m max_size=10g 
                     inactive=60m use_temp_path=off;

    upstream minio {
        server minio:9000;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://minio;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header x-minio-extract $http_x_minio_extract;
            proxy_pass_header Content-Type;
            
            # Cache configuration
            proxy_cache minio_cache;
            proxy_cache_valid 200 304 60m;
            proxy_cache_key "$scheme$request_method$uri";
            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}